version: '3.7'

services:
  dec2-mysql:
    image: mysql:5.7
    ports:
      - 3307:3306
      - 33070:33060
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./mysql/createDatabases.sql:/docker-entrypoint-initdb.d/createDatabases.sql
      - ./mysql:/etc/mysql/mysql.conf.d

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  dec2-kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:19092,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:19092,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3
    links:
      - zookeeper

volumes:
  ivy2:
    driver_opts:
      o: bind
      type: none
      device: $HOME/.ivy2
  sbt:
    driver_opts:
      o: bind
      type: none
      device: $HOME/.sbt
